### ISSUE TITLE
Mail de activación llega sin contenido

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#120]
Luego de registrarse en la página de Fansworld, el mail que llega a la casilla de correo con el link de activación, llega vacio. Ver archivo adjunto para más detalles.
![1](https://f.cloud.github.com/assets/4354380/467625/8c61a4fe-b67e-11e2-816b-eaf322f013b9.png)

**Comment by marucolona** [comment]
Lo mismo ocurre con el mail de reestablecer contraseña

**Comment by claudiorodriguez** [comment]
@juansanzone fijate, en local funciona bien, pero en svn.dodici.com.ar por algún motivo está pasando esto

**Comment by juansanzone** [comment]
Oka, ahora me pongo a verlo. Veremos que pasa
