### ISSUE TITLE
[DUP] Mail de activación llega sin contenido

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#121]
Luego de registrarse en la página de Fansworld, el mail que llega a la casilla de correo con el link de activación, llega vacio. Ver archivo adjunto para más detalles.
![1](https://f.cloud.github.com/assets/4354380/467643/1e3f1d5c-b67f-11e2-8bec-6c5203008ac3.png)

**Comment by claudiorodriguez** [comment]
Duplicado de #120
