### ISSUE TITLE
Ser Fan - Los botones que ya presione (ya eres fan) siguen apareciendo con el texto Ser Fan.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#122]
Cuando clickeo en "ser fan" por primera vez aparece YA ERES FAN, pero si refresco la pagina, el boton aparacera inhabilitado y con el texto "ser fan".
![fan](https://f.cloud.github.com/assets/4354380/467689/6e3f56ae-b680-11e2-8433-962a1cc85b44.png)

**Comment by maggiben** [comment]
![image](https://f.cloud.github.com/assets/2845947/467875/ae434df0-b685-11e2-80ed-12c5f5fe8c1c.png)
