### ISSUE TITLE
Ser Fan - Cuando el usuario se hace fan el numero de fans no se actualiza inmediatamente.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#124]
Cuando el usuario se hace fan el numero de fans no se actualiza inmediatamente sino una vez que se refresca la pagina. Ver archivo adjunto.
![1](https://f.cloud.github.com/assets/4354380/467825/344042fc-b684-11e2-868d-3ac0ed85e11d.png)

**Comment by marucolona** [comment]
Borre chaché y sigue sin actualizarse el numero de fans.

**Comment by anaibol** [comment]
maru, en que pagina ves eso?

**Comment by marucolona** [comment]
Yendo a la tab de idolos y clickeando en los 3 destacados o en el listado, solo funciona bien si ingreso al perfil de un idolo, si voy al perfil de un equipo no actualiza el numero de fans, salvo que recargue la pagina.

**Comment by marucolona** [comment]
Sigue pasando, borre cache en los exploradores que probe, pero aun no funciona

**Comment by claudiorodriguez** [comment]
No había actualizado el entorno, probalo ahora

**Comment by anaibol** [comment]
Ahi lo arregle maru

**Comment by marucolona** [comment]
Me sigue pasando
