### ISSUE TITLE
Actividad reciente - Aparece un titulo incorrecto.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#126]
Muchas veces al navegar por el sitio, al clickear en actividad reciente, aparece un titulo incorrecto:
"that.options.title"

![2 2](https://f.cloud.github.com/assets/4354380/467903/22e0ddbc-b686-11e2-978c-87c276e052b3.png)

**Comment by maggiben** [comment]
Esta arreglado en este commit: https://github.com/FansWorldTV/web/commit/024f83c1ee6085d32229df5c49920be7fe6a94ca fijate y si anda cerralo
