### ISSUE TITLE
Vista de mail de bienvenida a Fansworld

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#131]
Falta mail de bienvenida a fansworld, el template extender de Mail/notification_base.html.twig

La parte de backend: Issue #133

**Comment by lucasfc** [comment]
Jam! aca va el mail , quizas sufra cambio pro menores , no de tipografia ni de tamano.
Cualquier cosa me decis...
![captura de pantalla 2013-05-07 a la s 4 43 02 pm](https://f.cloud.github.com/assets/3672914/473461/1959c33a-b74e-11e2-80ac-1c2e00353bc9.png)

**Comment by anaibol** [comment]
Lucas, me pasas las imágenes de abajo? Las de tw, fb, g+, y pinterest porfavor
