### ISSUE TITLE
Subir Video - Invocando esta acción desde el muro, no funciona.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#135]
Subir Video - Cuando el usuario se encuentra en el muro y desde el estado clickea en Subir Video, invoca a una pagina que no esta funcionando. Ver attachment para más detalle.
![video desde muro](https://f.cloud.github.com/assets/4354380/472156/7b25a516-b72b-11e2-8803-75fad45b0d7d.png)

**Comment by anaibol** [comment]
No pude reproducir eso, parece que ya está arreglado
