### ISSUE TITLE
Dejar de ser fan - Si el usuario ingresa al perfil de un usuario/equipo/idolo el boton para dejar de ser fan no está.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#138]
Dejar de ser fan - Si el usuario ingresa al perfil de otro usuario/equipo/idolo y aparece el boton de "ser fan" luego de clickear en el, el boton se muestra gris e inactivo y si refresca la pagina directamente desaparece. Nunca puede dejar de ser fan de un usuario/equipo/idolo desde el perfil del otro.
![equipos](https://f.cloud.github.com/assets/4354380/473246/568727b2-b748-11e2-82c9-5657e6dc5aa3.png)

![dejar de ser f](https://f.cloud.github.com/assets/4354380/473118/e2d0e5b8-b744-11e2-92e5-0fb4fd992723.png)
![dejar de ser fan](https://f.cloud.github.com/assets/4354380/473119/e2f39860-b744-11e2-8596-a7e82c03a2a2.png)

**Comment by arraydude** [comment]
el objetivo es que si quieren dejar de ser fan , lo hagan desde "Mis Fans/Idolos" ...
