### ISSUE TITLE
Subir Video - Deberia haber un boton para subir video desde "Mis videos".

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#139]
Subir Video - Segun la especificación técnica de Fansworld, la funcion subir video debe ser invocada desde tres lugares:
"Invocado desde “Mis Videos”, mi muro, y el widget para subir"

Desde mis videos no hay botón para subir videos
![mis videos](https://f.cloud.github.com/assets/4354380/473336/927e37fe-b74a-11e2-82af-2995192a8481.png)

**Comment by arraydude** [comment]
Se sacó porque existe el botón de subir vídeo desde el menubar
