### ISSUE TITLE
Watch Later List - Cuando se termina de ver un video de los de la playlist, no desaparece de la misma.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#140]
Watch Later List-
Cuando el usuario termina de ver uno de los videos de la playlist de watch later, no desaparece, sino que sigue estando presente.

**Comment by marucolona** [comment]
desaparece de la lista cuando se refresca la pagina pero no cuando termina el video

**Comment by anaibol** [comment]
por ahora la funcionalidad es así maru!

**Comment by marucolona** [comment]
yo me guiaba por los documentos, pero si es así, cierre nomas, gracias!

2013/5/22 anaibol notifications@github.com
