### ISSUE TITLE
Ser Fan - Cuando el usuario ingresa a la tab de Idolos y quiere hacerse fan de alguno sin haber iniciado sesión, los botones permanecen en estado "loading".

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#152]
Ser Fan -
Si el usuario no no inició sesión e ingresa a la tab de Idolos y clickea Ser Fan en alguno o ingresando en el perfil de algun idolo, el boton de loading se queda constantemente en estado Loading y si bien se despliega el formulario de ingreso,  no hay ningun aviso que diga "debe iniciar sesión".
![la foto-1](https://f.cloud.github.com/assets/4354380/482770/bbe3f4fa-b8a6-11e2-8968-31cb751f2ee3.jpg)

**Comment by marucolona** [comment]
Sigue pasando

**Comment by arraydude** [comment]
me acabo de fijar y funciona bien, proba borrando cache

**Comment by marucolona** [comment]
ahi va, era el caché nomas,lo cierro, gracias
