### ISSUE TITLE
FilterType nuevo de usedInVideos

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#154]
Necesito que a demás de filtrar popular y latest, tambien permita por los que estoy etiquetado o estoy "siguiendo".

Para poder poner los tags para el listado de follow del nuevo home ( #34 ).

**Comment by juansanzone** [comment]
@arraydude @maggiben 

Ya esta disponible en el MASTER, en el servicio Tagger, el metodo:

trendingInRecommended($user, $limit=null, $offset=null)

Donde pueden recuperar los tags trending, asociados a los videos que sigue el usuario que le pasan como parametro.

Cualquier cosa me avisan :)
