### ISSUE TITLE
Canales - En los canales de estilos de vida y clubes la primer columna está desalineada.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#160]
Canales - 
En los canales de estilos de vida y clubes la primer columna está desalineada.
A primera vista el tamaño del primer video no es igual al resto y eso hace que no sigan un orden como el resto de las columnas.
![la foto](https://f.cloud.github.com/assets/4354380/495687/9d9b2466-bbce-11e2-83ef-1ea3331a713f.jpg)
![la foto-1](https://f.cloud.github.com/assets/4354380/495688/9d991cca-bbce-11e2-96fa-158dd2de21b0.jpg)

**Comment by anaibol** [comment]
esto desaparece en la nueva version de la home
