### ISSUE TITLE
Subir Video/ FIrefox - No se pueden subir videos en firefox.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#172]
Subir Video - FIrefox

No se pueden subir videos a firefox. En el debuger veo el siguiente mensaje:
[17:24:36.646] ReferenceError: reference to undefined property v.event.triggered @ http://fansworld.svn.dodici.com.ar/bundles/dodicifansworldweb/js/compiled/all.js:427

**Comment by maggiben** [comment]
Ocurre porque meteor trata de reescribir el document.domain (superdominio) y rompe la cadena de ejecución, esto no debería pasar si estuviera bien configurado el server, en otros lugares se comporta correctamente.

![image](https://f.cloud.github.com/assets/2845947/542505/936a9906-c225-11e2-9064-3fbcd2db034a.png)
