### ISSUE TITLE
Mail Welcome New FW User

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#174]
@anaibol van las imagenes y el preview del mail de bienvenida.
![fw_emails_welcome](https://f.cloud.github.com/assets/3672914/507354/1f4fad38-bd6e-11e2-9abd-bae9fadf3a5a.jpg)

**Comment by lucasfc** [comment]
Las imageens te las pase por mail. ahroa te paso una q faltaba.

**Comment by arraydude** [comment]
mismo que #131
