### ISSUE TITLE
Subir Foto/Video - Si clickeo en share sin haber copiado ningun link, el boton de share queda en loading.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#177]
Subir Foto / Video -
Si Clickeo en Share sin haber copiado ningun link, aparece link invalido pero el boton de share queda en loading.
![la foto](https://f.cloud.github.com/assets/4354380/509038/7f3541e2-bd99-11e2-99ea-d23c58b7e036.jpg)

**Comment by maggiben** [comment]
FIX: commit d9f9ebb3c95c00ec2935055632167e4479c7ffee
