### ISSUE TITLE
Subir Foto - Si elijo subir foto desde el muro, invoca al pop up de subir video pero el selector previo de subir foto o video queda en la pantalla.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#178]
EDIT CLAUDIO: En realidad hay que hacer que al hacer click en la cámara, se abra directamente el popup de subir vídeo

Subir foto - 
Si en el muro clickeo en la camara y elijo subir foto, aparece el pop up de subir video pero el pop up anterior para elegir subir video o foto permanece en la pantalla.
![la foto](https://f.cloud.github.com/assets/4354380/509062/27406b78-bd9a-11e2-9835-bd8fc513591b.jpg)

**Comment by claudiorodriguez** [comment]
En realidad hay que hacer que al hacer click en la cámara, se abra directamente el popup de subir vídeo

**Comment by maggiben** [comment]
fix en co: ab2943bae32dc9188be2f834ed733096104e3721
