### ISSUE TITLE
Subir Video/Foto - Si estoy en cualquier perfil sea de equipo o idolo y subo desde SUBIR VIDEO un contenido, taggea automáticamente a ese idolo/equipo. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#192]
Subir Foto/Video - 
Si estoy en el perfil de un Idolo o de un equipo como Godoy Cruz, y si voy al Uploader de video/foto que esta arriba a la derecha, al terminar de subir contenido (inclusive si es de youtube) se taggea automaticamente ese idolo o como el ejemplo Godoy Cruz, aunque no tenga nada que ver.
![la foto-1](https://f.cloud.github.com/assets/4354380/513416/7b33da46-be3d-11e2-8eeb-521cf2cb987d.jpg)

**Comment by maggiben** [comment]
@fansworld-claudio en algún momento esto había sido un feature requerido si mi memoria no me falla, ¿ Que sería apropiado hacer ahora, quitarlo ? salu2

**Comment by claudiorodriguez** [comment]
Working as intended
