### ISSUE TITLE
Subir Video - Los vídeos de extensión .mov, .avi o .mp4 que sube el usuario no se pueden ver.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#193]
Subir Videos -

Los videos .mov, .avi o .mp4 no se pueden ver, si bien muestra que los cargar cuando el usuario los sube, al reproducirlos el contador figura 00:00 y la previsualización de los mismos no funciona en las listas de videos o cuando se comparten en el muro.
![la foto-1](https://f.cloud.github.com/assets/4354380/514182/5167d586-be52-11e2-93ab-aaea10f7a6d4.jpg)

**Comment by claudiorodriguez** [comment]
@marucolona pasame un vídeo que haya fallado por mail o skype así lo pruebo a mano

**Comment by claudiorodriguez** [comment]
hay un bug en el plugin de subida, no está guardando el entry id de kaltura por algún motivo

**Comment by maggiben** [comment]
Había otro bug que hacia un submit del video más de una vez, pero ya esta, principalmete el entryID ahora es enviado junto al form
