### ISSUE TITLE
Mobile - API - search/term

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#195]
Necesitamos que la búsqueda indique, para el caso de perfiles, si el usuario de la session es seguidor de las entidades encontradas. Este funcionamiento, replica el caso de los listados: user/{id}/fans, idol/{id}/fans y team/{id}/fans.

No es necesario un extrafield, debe ocurrir siempre que se envie el user_id y token validos de un usuario autenticado.

**Comment by juansanzone** [comment]
@hernangonzalez  DONE!!  check!!  Cuando el resultado de la busqueda retorna usuarios y se indico un user_id, se añade el campo followed (true|false)

**Comment by hernangonzalez** [comment]
@juansanzone @ideastouch Buenas, de acuerdo a lo hablado, está funcionando la implementación unicamente para Usuarios. Necesitamos que se cumpla también para Idolós y Equipos. Gracias.

**Comment by juansanzone** [comment]
@hernangonzalez  Done! Listo para testear

**Comment by hernangonzalez** [comment]
Testeado, funciona. Gracias. cc @ideastouch
