### ISSUE TITLE
Implementacion del nuevo modelo de llamadas a user/teams  user/idols

### ISSUE THREAD

**Issue by juansanzone** [FansWorldTV/web#196]
Actualmente:
http://svn.dodici.com.ar/app_dev.php/api_v1/user/teams?target_id=2
http://svn.dodici.com.ar/app_dev.php/api_v1/user/idols?target_id=2

Esperado: (Target_id como parametro de la url)
user/{id}/teams 
user/{id}/idols

**Comment by juansanzone** [comment]
@hernangonzalez check it!!

**Comment by hernangonzalez** [comment]
Funciona, gracias.
