### ISSUE TITLE
user/teams  user/idols  -> Falta videoCount, slug no se usa

### ISSUE THREAD

**Issue by juansanzone** [FansWorldTV/web#197]
- Agregar videoCount
- Slug no se esta usando en Mobile

**Comment by juansanzone** [comment]
@hernangonzalez  check it!! 

El slug, va a seguir viniendo, porque viene del serializer de nuestro objeto/entidad.
Chequear videoCount

**Comment by hernangonzalez** [comment]
Chequeado, gracias.
