### ISSUE TITLE
Toolbar / Mis Fotos - El pop up para modificar el album dice upload photo.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#206]
Toolbar / Mis Fotos -

Al abrir la herramienta para modificar la info del album, el pop up di
![captura de pantalla 2013-05-20 a la s 16 12 29](https://f.cloud.github.com/assets/4354380/538035/76bfa502-c181-11e2-8234-e649c6aeee7e.png)
ce Upload Photo.

**Comment by maggiben** [comment]
fix commit: cef7cfe19f118e0419670f8ce33636043ef3fb04
