### ISSUE TITLE
Filtrar videos en perfil de Idolos/Clubes

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#21]
En el tab Videos tanto de idolos como de equipos estan apareciendo videos (todos, creo) Deberia filtrarse esa cantidad de videos por los asset q esten tagueado con una u otra entidad. Imagino q esto debe estar contemplado pero lo considero importante para el lanzamiento. adjunto
gracias
![Screen Shot 2013-03-18 at 3 22 49 PM](https://f.cloud.github.com/assets/3967972/308129/797b5722-96df-11e2-97c2-4fd050706522.png)
![Screen Shot 2013-03-18 at 3 23 51 PM](https://f.cloud.github.com/assets/3967972/308130/79848658-96df-11e2-9f41-03ec68a05548.png)

**Comment by juansanzone** [comment]
Los controlles que hacen el filtrado, deben recibir dos parametros mas: entityType & EntityId para poder realizar el filtrado de videos por equipo e idolo. 

Dado que es un Wrapper de JS de 3 Plugines, queda en @maggiben hacer esas modificaciones en el Javascript, para despues modificar los metodos Php de filtrado y adaptarlos a los nuevos parametros.

**Comment by juansanzone** [comment]
@maggiben  Hace un merge con el master benj!!! asi lo probamos en SVN y vemos si el problema esta resuelto :)

**Comment by juansanzone** [comment]
cerramos gracias @maggiben
