### ISSUE TITLE
Mobile - API - Reduce listings

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#216]
La tarea es reducir la información enviada, a fin de agilizar los requests. Datos no usados actualmente:
- Listados de videos => counters del author (videos, fans, etc).
- Listados de entidades => Splash image.

Esto aplica tambien a las búsquedas.

Gracias. (cc @ideastouch )

**Comment by claudiorodriguez** [comment]
@hernangonzalez check please
