### ISSUE TITLE
Acceso a términos y condiciones - La página no es iphone dedicado

### ISSUE THREAD

**Issue by ideastouch** [FansWorldTV/web#217]
Térmimos y condiciones - 
La pagina actual de términos y condiciones no es iphone dedicado, puedo ingresar a ver el mismo contenido de la web.
![la foto](https://f.cloud.github.com/assets/4354380/483563/b937a94e-b8c0-11e2-8f8d-17f389d2f627.png)

**Comment by claudiorodriguez** [comment]
http://svn.dodici.com.ar/terms/text
