### ISSUE TITLE
Implementar opciones (cambiar splash/perfil) en Perfil de User

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#22]
Adjunto una vista de lo que propongo para q el usuario tenga una posibilidad mas "a mano" de modificar las imagenes de su perfil

L
![Screen Shot 2013-03-18 at 5 33 07 PM](https://f.cloud.github.com/assets/3967972/308137/988b6d8c-96df-11e2-9b82-85c4b1a66fd5.png)

**Comment by maggiben** [comment]
Y si mejor esos botones despliegan un menu que te permita elegir fotos de otras fuentes (preexistenes [de un album], desde una URL, o desde un archivo) ?
También seria logico que el backend guardara estas fotos dentro de un album como lo hace facebook en fotos de perfil... solo decia...

**Comment by claudiorodriguez** [comment]
@maggiben sí, está contemplado para el futuro eso del álbum "fotos de perfil". Lo del menú, y url (hacerlo más tipo imgur), son ideas interesantes, en algún momento revisitaremos estas funciones.
