### ISSUE TITLE
Mobile - API - Fan Add/Remove counters

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#220]
Para los siguientes métodos, agregar como respuesta la cantidad actualizada de fans. 

/user/fan/add
/user/fan/remove

cc @ideastouch

**Comment by claudiorodriguez** [comment]
@hernangonzalez ahora devuelve un array o único {id: int, fanCount: int} por cada user/team/idol (lo agregué también a team/fan/\* y a idol/fan/*)

**Comment by hernangonzalez** [comment]
Para el auhor se sigue enviando los contadores:
http://svn.dodici.com.ar/app_dev.php/api_v1/video/list?extra_fields=author

**Comment by claudiorodriguez** [comment]
Eso es el issue #216, lo sigo allá
