### ISSUE TITLE
Ver video - El video trailer de entrevistas en ingles no esta funcionando. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#221]
Ver video -

El video trailer de entrevistas en ingles esta fallando. 

En la app aparece el siguiente error:  
(400) - Entry id "1_9bsnlkd3" not found

![captura de pantalla 2013-05-21 a la s 16 26 59](https://f.cloud.github.com/assets/4354380/544332/d3c30a3e-c24c-11e2-87af-94be1bbd78cd.png)
![captura de pantalla 2013-05-21 a la s 16 27 07](https://f.cloud.github.com/assets/4354380/544333/d3c85264-c24c-11e2-9950-24ccf6daa561.png)

**Comment by claudiorodriguez** [comment]
Es porque alguien lo borró de Kaltura, está bien, normalmente no pasaría esto
