### ISSUE TITLE
Mobile - API -  User Team & Idol list {image}

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#222]
Listing of *_user{id}/team *_ or **user/{id}/idols send wrong image parameter, as opposed to  idol/{id} or team/{id}.

Example:
FAIL - http://svn.dodici.com.ar/app_dev.php/api_v1/user/2/teams
OK - http://svn.dodici.com.ar/app_dev.php/api_v1/team/2

**Comment by claudiorodriguez** [comment]
@hernangonzalez fixed
