### ISSUE TITLE
Reemplazar slider en landing.

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#224]
sobreescribir el slider carousel-lifestyle.png con este 
![carousel-lifestyle](https://f.cloud.github.com/assets/3672914/549160/ce2d85b6-c2f3-11e2-9ee9-5a7e884e49eb.png)R

**Comment by claudiorodriguez** [comment]
@lucasfc Lo cambié, y de pasó cambié los png a jpg. Para imágenes tipo vectoriales con colores sólidos (texto, íconos, logos), es mejor PNG, pero para fotos es mejor JPG, la diferencia a la misma calidad es de 150kb del jpg vs 1.2mb del png.

**Comment by lucasfc** [comment]
gracias!
