### ISSUE TITLE
Subir video - No debería haber algo que indique que se subio o se terminó de cargar el video? 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#234]
Subir video -

Cuando el usuario sube el video, se muestra una barra de carga, que si bien se muestra llena, no hay ningun indicador textual que diga que el video terminó de cargarse. No debería haber algun otro indicador? 
![captura de pantalla 2013-05-23 a la s 11 15 41](https://f.cloud.github.com/assets/4354380/554871/a6e704ee-c3b3-11e2-889e-4d73fa0dbc44.png)

**Comment by maggiben** [comment]
Ahora va mejor @marucolona ?:

![image](https://f.cloud.github.com/assets/2845947/555270/170740b6-c3bb-11e2-99d8-f808550082bf.png)

**Comment by maggiben** [comment]
TODO: ver el texto del mensaje e incluirlo en el sistema de translate
