### ISSUE TITLE
Search Predictivo

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#238]
Lo q se hablo de la predictiva..
escucho observaciones si las hubiera..
Creo que el flow se entiende..

![captura de pantalla 2013-05-23 a la s 12 29 01 pm](https://f.cloud.github.com/assets/3672914/555448/59e0f1bc-c3bf-11e2-9aaf-d97d9fb35b81.png)

**Comment by claudiorodriguez** [comment]
@arraydude @lucasfc A mí me parece bien. Tener en cuenta que las palabras de arriba de todo son tags y/o search-history con un mínimo de popularidad.

**Comment by lucasfc** [comment]
Claro , habria q ver en casa caso. Y habria q ver q se muestra antes y q se muestra despues.
Otra cosa que creo que habria  hacer es priorizar orden de perfiles segun la seccion dodne el user se encuentre_
Estas en Canales , priorizaria los request de TV . En Perfiles el de idolos y asi... es una locura_
L
