### ISSUE TITLE
Perfil - Al ingresar al perfil de un usuario, se ve que el user subio cierta cantidad de videos, pero no se muestra ninguno.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#242]
Perfil.

Si el usuario ingresa al perfil de otro usuario, la informacion muestra que tiene cierta cantidad de videos subidos pero no se ve ninguno.

Este issue estaba subido en mobile, pero Gus pidio se suba acá ya que es un problema del servidor. 
![53835ec6-c22b-11e2-95bc-3d47728b1b03](https://f.cloud.github.com/assets/4354380/562464/daaca1d8-c4aa-11e2-85cd-82adf35bfee7.png)

**Comment by arraydude** [comment]
Este issue tendría que estar dentro del repo de mobile

**Comment by hernangonzalez** [comment]
Nahuel, Maru lo creo porque el tema es que lo que informa mal la cantidad el API. @arraydude @marucolona
@ideastouch agregas la info del API. Gracias

**Comment by arraydude** [comment]
Bueno , entonces lo tageo con "api"

**Comment by juansanzone** [comment]
@hernangonzalez  Pasame la query de API que estas haciendo, en la cual te devuelve este count erróneo

**Comment by hernangonzalez** [comment]
@juansanzone, Lo tiene asignado @marucolona porque está viendo si ocurre aún. Si lo reproducimos te lo enviamos. Gracias.

**Comment by juansanzone** [comment]
@marucolona   este es el issue relacionado con el issue de api #318  no ? Podemos cerrar este?? Y continuar en aquel.  ?

**Comment by marucolona** [comment]
Ok, cierro este juancho! Queda asentado en el #318
