### ISSUE TITLE
Hacerse fan y tiempo de actualización en el servidor

### ISSUE THREAD

**Issue by ideastouch** [FansWorldTV/web#246]
Si me hago fan de alguien y luego de recibir el OK de la operación pregunto por los fan de ese alguien no aparezco como fan hasta pasado unos segundos largos.

![la foto](https://f.cloud.github.com/assets/4354380/568498/a315ed0a-c6db-11e2-9972-42a710c47759.png)
![la foto-1](https://f.cloud.github.com/assets/4354380/568499/a312620c-c6db-11e2-9cb2-a58bdaa735bb.png)

**Comment by claudiorodriguez** [comment]
@ideastouch @hernangonzalez el único caso en el que veo que pasa esto es cuando el usuario está en modo restringido. La solicitud de amistad no está aprobada, por eso no le pone el followed y no aparece como fan hasta que se apruebe. Acordemos una forma de representar esta situación

**Comment by claudiorodriguez** [comment]
Sigue en #260

**Comment by ideastouch** [comment]
Hay un error y como quizas tenga que ver con este arreglo te te reabro este issue en lugar de crea uno nuevo.
1. Estoy pidiendo la lista de fans del usuario 8 y estoy logueado con el usuario 14.
2. Recibo una sola persona y en este caso es el usuario 32 y el mismo tiene la variable followed en NONE, osea que el usuario 14 no lo está siguiendo.
3. Pido la lista de fans del usuario 32 y entre ellos recibo el usuario 14, lo cual es una contradicción en relación a la info recibida en el punto anterior.

Abajo te copio los request:
 http://svn.dodici.com.ar/app_dev.php/api_v1/user/8/fans?page=0&limit=10&api_key=abcdef&api_signature=e0e0dd087aeae2cf1180e6fb497c4d95375a1971&api_timestamp=1369858926&device_id=iPhone%20Simulator&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1
y
http://svn.dodici.com.ar/app_dev.php/api_v1/user/32/fans?page=0&limit=10

**Comment by ideastouch** [comment]
La lista de dans de un usuario indica "x" fans y el fan counter de cada uno de ellos no es consistente con la cantidad de fans que trae su lista.

En la lista del 8 viene un solo fan el 32 con fan counter igual a 6:
http://svn.dodici.com.ar/app.php/api_v1/user/8/fans?page=0&limit=10&api_key=abcdef&api_signature=892e4a23f1326c520449bb857c30b75171bb6172&api_timestamp=1370028925&device_id=iPhone%20Simulator&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1

En la lista del 32 vienen 7 fans:
http://svn.dodici.com.ar/app.php/api_v1/user/32/fans?page=0&limit=10&api_key=abcdef&api_signature=f7c1870bff1fea8a97e77fdadf3dcaf989138ad1&api_timestamp=1370028805&device_id=iPhone%20Simulator&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1
