### ISSUE TITLE
Inconsistencias entre los counters del usuario y las listas de video y/o fan

### ISSUE THREAD

**Issue by ideastouch** [FansWorldTV/web#248]
El último escenario que pasó esto fue: pido detalles de un usuario y me da 6 videos y 6 fans, mas luego cuando pido la lista de fans solo trae 4. 

User request:
http://svn.dodici.com.ar/app_dev.php/api_v1/user/8/fans?page=0&limit=10&api_key=abcdef&api_signature=44be88aedf0829201f44d7eb32266c1b82a91543&api_timestamp=1369667176&device_id=iPhone%20Simulator&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1

Videos request:
http://svn.dodici.com.ar/app_dev.php/api_v1/user/32/videos?page=0&limit=10&api_key=abcdef&api_signature=d4b0f40799b80c66b1c782bcaa9c851d55f1b11a&api_timestamp=1369667215&device_id=iPhone%20Simulator&extra_fields=author%2Cduration%2Cwatchlisted&imageformat=wall&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1

Following request:
http://svn.dodici.com.ar/app_dev.php/api_v1/user/32/fans?page=0&limit=10&api_key=abcdef&api_signature=60b2f7036782ca735ea3b70c5781d521592410db&api_timestamp=1369667255&device_id=iPhone%20Simulator&user_id=14&user_token=067a9ae6bd9d83d36a91f316e6f8a1762bc641e1

**Comment by claudiorodriguez** [comment]
@ideastouch Ok, creo que lo arreglé, fijate por favor
