### ISSUE TITLE
Comentar / Muro - Cuando el user solo escribe tags y no el mje al querer publicar el cartel se muestra vacio.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#251]
Comentar / Muro -

Cuando el usuario esta en su muro y escribe solo tags y no el mje, al querer publicarlo el cuadro del mje aparece vacio (arriba a la derecha)  
![captura de pantalla 2013-05-28 a la s 10 24 05](https://f.cloud.github.com/assets/4354380/572446/85b08d82-c79a-11e2-8970-fa6a50a964ee.png)

**Comment by maggiben** [comment]
![image](https://f.cloud.github.com/assets/2845947/618367/2c1ff4d6-ceb3-11e2-9c37-0f77e1823970.png)
