### ISSUE TITLE
Subir Foto - Aparece un boton de upload en el pop up. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#258]
Subir foto -

Aparece un boton de upload en el pop up. 
![captura de pantalla 2013-05-28 a la s 15 56 49](https://f.cloud.github.com/assets/4354380/574531/d253ee10-c7ca-11e2-9e2d-944417b3636f.png)

**Comment by maggiben** [comment]
fix commit: 448dcfc86c63a22ab7b4732dc29b08c8f909f5bb
Tmb se quito la restricción en el ancho del infobox para que ocupe el espacio restante en el dialogo (sin modificar el thumbnail)
El upload comienza una vez que la api lee la imagen (TODO: probar en distintos browsers)
