### ISSUE TITLE
Mobile - API - Recommended Video List - Empty

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#261]
El siguiente usuario **29** trae 0 videos recomendados:

{
result: [ ],
metadata: {
uri: "http://svn.dodici.com.ar/app.php/api_v1/video/list?api_key=abcdef&api_signature=d30639082132ae1a5c08c30e000cde62453d4fb9&api_timestamp=1369917444&device_id=iPhone&extra_fields=author%2Cduration%2Cwatchlisted&imageformat=wall&limit=10&page=0&recommended=1&user_id=29&user_token=31ccf16334fe522795af53291494b37083198c64",
method: "GET",
parameters: {
query: {
page: "0",
limit: "10",
api_key: "abcdef",
api_signature: "d30639082132ae1a5c08c30e000cde62453d4fb9",
api_timestamp: "1369917444",
device_id: "iPhone",
extra_fields: "author,duration,watchlisted",
imageformat: "wall",
recommended: "1",
user_id: "29",
user_token: "31ccf16334fe522795af53291494b37083198c64"
},
request: [ ]
},
pagination: {
limit: "10",
offset: null,
page: 0,
sort: "weight",
sort_order: "DESC",
count: 0
}
}
}

**Comment by claudiorodriguez** [comment]
@hernangonzalez en realidad implementé una salvaguarda, si no encuentra vídeos recomendados (que es posible con usuarios completamente nuevos), trae todo
