### ISSUE TITLE
Dejar de ser fan - No se pueden eliminar fans de la web. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#262]
Dejar de ser fan.

Al querer remover algun fan, se muestra un cartel de que la acción no pudo llevarse a cabo. 
![screen shot 2013-05-30 at 9 32 46 am](https://f.cloud.github.com/assets/4354380/584816/bfe6d4be-c927-11e2-9d40-91d6679bce3c.png)

**Comment by anaibol** [comment]
Esto sigue sin andar? Yo pude remover fans desde /my/fans
