### ISSUE TITLE
Mobile - API -  Share capture on Fansworld.tv

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#264]
Siguiendo con la implementación de la captura
/video/upload/entry

Necesitamos el API que comparta un video en fansworld.tv con:
- Lista de usuarios a quien compartir
- Flag para pegar en el propio muro 
- otros (?)

**Comment by juansanzone** [comment]
/**
     \* [signed] Share Video
     *
     \* @Route("/video/share/{id}", name="api_v1_video_share")
     \* @Method({"POST"})
     *
     \* Post params:
     \* - user_id: int
     \* - [user token]
     \* - <optional> title: String
     \* - <optional> shareidols: comma-separated Ids (String)
     \* - <optional> shareteams: comma-separated Ids (String)
     \* - <optional> shareusers: comma-separated Ids (String)
     \* - <optional> wall: boolean,
     \* - <optional> tofb: boolean,
     \* - <optional> totw: boolean,
     \* - [signature params]
     */
