### ISSUE TITLE
Splash - La imagen que viene como splash por default esta desalineada. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#265]
Splash - 

La imagen que viene por default si el usuario no subio ninguna, no esta alineado y el logo de fansworld no se ve practicamente.  
![captura de pantalla 2013-05-31 a la s 15 39 25](https://f.cloud.github.com/assets/4354380/592691/b4638aec-ca21-11e2-92c7-39c36b190639.png)

**Comment by lucasfc** [comment]
Poner esta como cover default.
![profile_cover_no_image](https://f.cloud.github.com/assets/3672914/878712/23253af4-f919-11e2-806c-36e208334eca.jpeg)
