### ISSUE TITLE
[ Perfiles ] Nueva sección

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#272]
![perfilesjpg](https://f.cloud.github.com/assets/631997/600928/ea9ad0bc-cc73-11e2-8cf9-eb17c6a310c4.jpg)

**Comment by arraydude** [comment]
follow me @lucasfc

**Comment by lucasfc** [comment]
@arraydude Cualquei duda metela aca. asi queda todo en el issue!

**Comment by arraydude** [comment]
@lucasfc con respecto a los perfiles que son del doble de tamaño, que hacemos ?... porque las entidades no tienen un campo de highlight

**Comment by lucasfc** [comment]
Cuando se decidio esto se lo hizo claramente con un fin estetico. (error)
Creo que hay que destacar lo q mas videos tenga asignados. Tambien los fans son importantes.
Podremos ordenarlos por cantidad de fans y destacar los 5 q mas videos tengan?
@arraydude Como lo ves?

**Comment by arraydude** [comment]
@lucasfc  o sea los primeros 5 elementos que sean el doble de tamaño ?

**Comment by claudiorodriguez** [comment]
@lucasfc @arraydude 
Hagamos así: que el cuadro de arriba traiga los perfiles que últimamente más tuvieron actividad (ej: Pedro Futbolista nunca fue famoso, pero esta última semana subieron un vídeo en el que hace jueguito y explotó en fans/vídeos/visitas), y los agrandados sean los que entre esos, más realmente populares son (por ahí aparece Messi). Que el cuadro de abajo, paginado, sea por popularidad (weight) directamente.

**Comment by arraydude** [comment]
@maggiben follow this

**Comment by arraydude** [comment]
@lucasfc Lucas, en el bloque de "Populares" el hover de cada elemento es como el de arriba ?, todos los elementos serian del mismo tamaño , no? ( a diferencia del primer bloque )

**Comment by lucasfc** [comment]
@arraydude Sip! el comportaeinto es igual y el layout es igual con al salvedad q hablamos recien
En destacados SOLO mostramos indicador de videos u en Populares SOLO el de fans
