### ISSUE TITLE
Compartir Foto/Album - No se puede compartir foto o album. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#273]
Compartir foto/ album -

No se puede compartir foto o álbum.
Pareciera como si al clickear en compartir ademas hiciera la request 2 veces, en vez de una. 
![captura de pantalla 2013-06-03 a la s 14 39 08](https://f.cloud.github.com/assets/4354380/600963/e035c5c2-cc74-11e2-9f28-f4a1594a2566.png)

**Comment by anaibol** [comment]
Si funciona!
