### ISSUE TITLE
Ser fan - Si ingreso a la lista de equipos y clickeo en ser fan, el boton no cambia de estado. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#275]
Ser fan -

Ingresando a equipos y haciendo click en ser fan de cualquier equipo, el boton no cambia de estado , pero si ingreso al perfil se muestra al usuario agregado.
![captura de pantalla 2013-06-03 a la s 15 43 10](https://f.cloud.github.com/assets/4354380/601332/e6eb9366-cc7d-11e2-8835-4929d4747901.png)
![captura de pantalla 2013-06-03 a la s 15 43 22](https://f.cloud.github.com/assets/4354380/601333/e75b2fb4-cc7d-11e2-9c86-3ef172d9ab81.png)

**Comment by arraydude** [comment]
El listado de equipos ya no va mas, ahora esta todo concentrado en "Perfiles"
