### ISSUE TITLE
Toolbar/Mis Equipos - No funciona dejar de ser fan de mis equipos. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#276]
Toobar - Mis equipos.

Al seleccionar dejar de ser fan en cualquier equipo que sigo, no se actualiza el estado, cuando refresco la pagina, el equipo desaparece.
![captura de pantalla 2013-06-03 a la s 16 00 48](https://f.cloud.github.com/assets/4354380/601433/0006148c-cc80-11e2-92e5-e23c5aea4bc0.png)

**Comment by anaibol** [comment]
no more toolbar
