### ISSUE TITLE
[ Perfiles ] Backend

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#277]
Para la sección nueva de perfiles andamos necesitando que los perfiles ( idol y team ), tengan la relación con un genre, para luego filtrarlo con sus respectivos metodos de repositorio:
- search para traer los perfiles ordenados por popularidad, con un limit y offset para poder paginarlo.
- search para traer los perfiles que mas actividad tuvieron ( https://github.com/FansWorldTV/web/issues/272#issuecomment-18866446 ), y que la lista tenga marcados los N perfiles con mas popularidad

Ref: #272

**Comment by juansanzone** [comment]
Hey amiguitus: @maggiben  @arraydude  !!
- Las entidades idol y team ya soportan asociacion de genero (genre_id) 
- Se creo el repositorio Profile y el controller Profile (definan ahi funciones Ajax relacionadas con perfiles)

Se creo el siguiente metodo ajax en ProfileController.php para buscar perfiles (idol y team) populares y por actividad soportando filtro de genero:
-     \*  Get params:
-     \*  - type: 'all' | 'idol' | 'team'
-     \*  - filterby: 'popular' | 'activity'
-     \*  - genre: (Int) genreId of parent(genre) | genreId of child(subgenre) | null
-     \*  - limit (Int) | null
-     \*  - offset (Int) | null
-     \*  @Route("/ajax/getProfiles", name="getprofiles_ajaxget")

Ver si ese metodo que cree les sirve para llamarlo por JS y sino retoquenlo,
fijense que ese metodo ajax utiliza una funcion del nuevo repo llamado "profile" ->  method "latestOrPopular"
- Ejemplo de como utilizar la funcion latestOrPopular del repo Profile desde un controller
  
  $entities = $this->getRepository('Profile')->latestOrPopular($type, $filterby, $genre, $limit, $offset);
