### ISSUE TITLE
Agregar género a subida vídeo

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#278]
Hay que agregarle el combo de género a la subida de vídeo. Cuando se sube un vídeo, un usuario tiene que elegir un genre y un videocategory. No puede elegir genre que sea "padre" (parent=null), tiene que ser un genre "hijo". Pero en el combo tienen que aparecer estructurados.

**Comment by maggiben** [comment]
en co #89a5c9929b6d388bc670df702e77137331078bba
