### ISSUE TITLE
Mobile - API -  User following Users/Idols/Teams

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#281]
Necesitamos un API que permita listar los perfiles que sigue (fans) un usuario, incluidos idolos y equipos. Un ejemplo de resultados, es la busqueda de entidades donde se informan las 3 colecciones.

**Comment by juansanzone** [comment]
/**
     \* User - follow
     *
     \* @Route("/user/{id}/follows", name="api_v1_user_follow")
     \* @Method({"GET"})
     *
     \* Get params:
     \* - <optional> limit: int (amount of entities to return, default: LIMIT_DEFAULT)
     \* - <optional> offset/page: int (amount of entities to skip/page number, default: none)
     *
     \* @return
     \* array(array('user'=> array(), 'idol'=> arrray(), 'team' => array()))
    */

**Comment by hernangonzalez** [comment]
2 issues:
- Mal los resultados. Para el usuario con id 2, por ej, solo trae usuarios, y no idolos o equipos. Para el caso id 15, trae 1 solo idolo. Faltan mas idolos y equipos.
- La respuesta de la imagen está mal. Debria ser así: imagen { id, url }

**Comment by arraydude** [comment]
Referenciado: #308

**Comment by hernangonzalez** [comment]
Update:
- Lo que falta solucionar es como se envia la info de la imagen. Es bloqueante. 

Gracias

**Comment by juansanzone** [comment]
@hernangonzalez  podemos cerrarlo iturbe?

**Comment by hernangonzalez** [comment]
@juansanzone cierre nomas.

**Comment by hernangonzalez** [comment]
Responses inside user are encapsulated inside a single array each. Example:

---

result: {
user: [10]
0:  [1] //  <---- This is an extra level that should NOT be present.
0:  {
id: 13
title: "Juan Sanzone"
image: {
id: 363
url: "http://svn.dodici.com.ar/uploads/media/default/0001/01/thumb_363_default_small_735fde9737ccb2c630bd957171ebca8fab0eb5da.jpg"

## }

**Comment by juansanzone** [comment]
@hernangonzalez  ready por test

**Comment by juansanzone** [comment]
@hernangonzalez  test!

**Comment by hernangonzalez** [comment]
@juansanzone testeado, gracias!
