### ISSUE TITLE
Mobile - API - Genres list - Missing info

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#284]
Falta la info de paginado al listado de genres:
http://svn.dodici.com.ar/app_dev.php/api_v1/video/genres/list

Ejemplo de de video/list:

pagination: {
limit: 10,
offset: null,
page: 0,
sort: "weight",
sort_order: "DESC",
count: 10
}

**Comment by claudiorodriguez** [comment]
@hernangonzalez Ok, le agregué paginado, y cambié la ruta a /video/genres

**Comment by hernangonzalez** [comment]
Por no usamos el /list ? Es más RESTful estandar.

**Comment by hernangonzalez** [comment]
Nop, parece que me equivoque... http://en.wikipedia.org/wiki/Restful#RESTful_web_APIs
