### ISSUE TITLE
Mobile - API -  Upload not showing up

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#293]
Uploaded videos do not show up in Fansworld.tv.
Fansworld API & Kaltura return success.

Ref: https://github.com/FansWorldTV/Mobile-iOS/issues/300

**Comment by claudiorodriguez** [comment]
Era un error de configuración de kaltura por flavors requeridos, a partir de ahora con nuevos vídeos debería funcionar bien
