### ISSUE TITLE
Errores consola home

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#296]
Desloggeado en svn.dodici.com.ar en la home me está tirando esto, se queda un loading colgado, calculo que será por el home/ajax/filter, fijate con @maggiben si hace falta algo de js

GET http://svn.dodici.com.ar/ajax/get-notifications 500 (Internal Server Error) all.js:427
GET http://svn.dodici.com.ar/ajax/getactivity-feed?page=1 403 (Forbidden) all.js:427
GET http://svn.dodici.com.ar/home/ajax/filter?null=NaN 500 (Internal Server Error)

**Comment by arraydude** [comment]
@maggiben Con respecto a la llamada a get-notifications y getactivity-feed , si estas deslogueado el JS no lo deberia estar llamando ya que si mal no recuerdo uno es para las notificaciones y el otro para el widget de actividad ( los cuales no aparecen si no estas logueado )

**Comment by arraydude** [comment]
Se pusheo al branch iss296 el fix de la parte del controller, solo faltaria NO mostrar el block de followed de parte del frontend cuando estes deslogueado.

@maggiben
