### ISSUE TITLE
Mobile - API -  Image sizes

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#297]
We need to create custom sizes to cover mobile needs. All size must maintain the aspect rate, filling the are, and cropping as needed. These sizes are the following:
1. Video - Thumbnail
   - **mobile_320x208** -> width: **640**, height: **416**
2. User/Team/Idol - Picture
   - **mobile_150x150** -> width: **300**, height: **300**
   - **mobile_65x65** -> width: **130**, height: **130**
   - **mobile_30x30** -> width: **60**, height: **60**
3. User/Team/Idol - Splash
   - **mobile_320x210** -> width: **640**, height: **420**

**Comment by juansanzone** [comment]
Ready for test @hernangonzalez

**Comment by hernangonzalez** [comment]
@juansanzone testeado, gracias!

**Comment by hernangonzalez** [comment]
Pasé los tamaños mal, deben ser el doble. Actulicé la descripción tambien. Muchas Gracias.

**Comment by juansanzone** [comment]
Video - Thumbnail

mobile_320x208 -> width: 6400, height: 416  ???   

6400 ??? o  650??   

@hernangonzalez

**Comment by juansanzone** [comment]
perdon 640

**Comment by hernangonzalez** [comment]
ups, corrected

**Comment by juansanzone** [comment]
otra cosa.. vos los vas a llamar con esa clave?? o sea al de 640 x 416, como  mobile_320x208  ??? o seria mobile_640x416  ?

**Comment by hernangonzalez** [comment]
Si, la clave es en puntos, y el tamaño final en pixel. Es como trabajamos nosotros. Gracias.

**Comment by juansanzone** [comment]
@hernangonzalez  ready!
