### ISSUE TITLE
+ Blog

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#304]
En un futuro no muy lejano necesitamos un blog para prensa, lanzamientos , mejoras, etc.
De momento a Valeria le vendria muy bien.
De ser posible q sea un WP. El tema lo puedo ver despues.
gracias

**Comment by lucasfc** [comment]
Sugerencia 
http://blog.fansworld.tv/ o fansworld.tv/blog

**Comment by claudiorodriguez** [comment]
Datos enviados por mail. blog.fansworld.tv

**Comment by lucasfc** [comment]
@fansworld-claudio Esta hosteado por nos o lo tenemos afuera_
Necesito meterle al menos un header (logo), como hacemos?
![captura de pantalla 2013-06-24 a la s 2 45 02 pm](https://f.cloud.github.com/assets/3672914/697020/5a34fc0e-dcf5-11e2-8698-e61770fac2cc.png)
