### ISSUE TITLE
Mobile - API -  Report Video - Inform report

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#307]
Para el caso que el video ya fue reportado con anterioridad, necesitamos que el API nos lo informe en la respuesta. Puede ser con un error, o algún mensaje en la respuesta.

Gracias!

**Comment by juansanzone** [comment]
@anaibol fijate anibal, si podes agregarle eso. Cualquier cosa consultame.

**Comment by juansanzone** [comment]
@hernangonzalez  testeado! OK, lo cierro

**Comment by ideastouch** [comment]
Juan, supongo que pusiste código de error 420, pero de todas formas podemos generalizar de siempre poner este dato cuando cerrás el issue. Y confirmame porfa´ lo de código 420.
Gracias!
Gus

**Comment by juansanzone** [comment]
ajam. perfecto..  si efectivamente.

cuando el video fue reportado con exito por el user, tenes response: true.

cuando, el video ya fue reportado, y quieren volver a reportarlo, da error 420. 'User already report video'

**Comment by hernangonzalez** [comment]
testeado!
