### ISSUE TITLE
Mobile - API - Upload needs Tag parameter.

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#309]
El metodo /video/upload/entry necesita tambien recibir los tags de usuarios/idolos/equipos en el video.

**Comment by juansanzone** [comment]
Ahora tambien se recibe por POST:

tagtexts: (String) tag1, tag2, tag3, tagN (separados por comas)
tagidols: (String) id1, id2, id3, idN (separados por comas)
tagteams: (String) id1, id2, id3, idN (separados por comas)
tagusers: (String) id1, id2, id3, idN (separados por comas)

**Comment by juansanzone** [comment]
Ready for test! @hernangonzalez

**Comment by hernangonzalez** [comment]
@juansanzone testeado, gracias!
http://svn.dodici.com.ar/app_dev.php/api_v1/video/1344?extra_fields=tagged_users,tagged_teams,tagged_idols,tagged_tags
