### ISSUE TITLE
Agregar botón suscribir a canal

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#326]
Agregar un botón de suscribirse a canal, preguntarle a Lucas si lo podemos meter en la home, sino en el detalle de vídeo o los dos lados

**Comment by lucasfc** [comment]
adjunto captura de donde deberia esta posicionado el bt de suscribir al canal
![captura de pantalla 2013-07-08 a la s 11 20 23 am](https://f.cloud.github.com/assets/3672914/761701/19a7d2f8-e7d9-11e2-80b0-bb25d9a78c3b.png)
