### ISSUE TITLE
Botón like en detalle video siempre visible

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#339]
Hacer que el botón estrellita (like) siempre aparezca en el detalle de vídeo, hoy por hoy cuando no estás loggeado desaparece. Hacer que al darle click desloggeado haga lo mismo que el watch later.

**Comment by arraydude** [comment]
@maggiben Benja ya solucione la parte del twig, solo faltaria que hagas tu magia con el bind para el data-login-required

PD.: branch iss339
