### ISSUE TITLE
FB Connect - La foto de perfil de FB no se actualiza en la pagina de FW.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#355]
FB Connect

Si cambi la foto de perfil de FB, logueandome y deslogueandome de la web de FW y de FB, en FW no se actualiza la foto. 

![captura de pantalla 2013-07-10 a la s 11 25 49](https://f.cloud.github.com/assets/4354380/775219/fb03847e-e96c-11e2-9b76-7e62c9f121a2.png)
![captura de pantalla 2013-07-10 a la s 11 26 03](https://f.cloud.github.com/assets/4354380/775220/fb35b2f0-e96c-11e2-974b-eb30b7748317.png)

**Comment by arraydude** [comment]
@marucolona La imagen la toma la primera vez que te conectas, despues no es que estan sincronizadas....

**Comment by marucolona** [comment]
@arraydude cerralo, si lo habia subido hace tiempo pero despues vi que era así, gracias
