### ISSUE TITLE
Calidad thumbs

### ISSUE THREAD

**Issue by claudiorodriguez** [FansWorldTV/web#356]
Revisar calidad de thumbs en:
- Home (los grandotes se ven feo)
- Perfiles (los grandotes)
- Sidebar en un detalle de perfil (avatares)
- Otros lugares de alto tránsito

En general parece que usa formatos de thumb más chiquitos de lo que debe. Es preferible pecar de exceso.

**Comment by lucasfc** [comment]
![captura de pantalla 2013-07-10 a la s 11 40 53 am](https://f.cloud.github.com/assets/3672914/775313/d1e4f10c-e96e-11e2-9b97-810429f73592.png)

**Comment by lucasfc** [comment]
@arraydude tenemos que ver q hacemos con foto de portada. Entiendo y comprendo q tiene solo 500px de ancho. Quizas mas adelante podamos subirla mas grande, hoy veremos como la piloteamos.
