### ISSUE TITLE
Detalle de Video con componentes sociales.

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#36]
Aqui un preview.
![Captura de pantalla 2013-04-04 a la s 1 35 12 PM](https://f.cloud.github.com/assets/3672914/340058/93112efc-9d45-11e2-9821-f366550c6b05.png)

**Comment by claudiorodriguez** [comment]
La parte del call to action se trata en #17 - este issue se refiere a los vídeos "fans que sigues", y el rediseño de la parte de abajo
