### ISSUE TITLE
Comportamiento BT + y SER FAN

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#364]
el bt de ser fan hace unas cosas muy raras cuando le das click.
![captura de pantalla 2013-07-10 a la s 2 42 28 pm](https://f.cloud.github.com/assets/3672914/776514/2f5dbaee-e988-11e2-8a5e-1dadc6e34262.png)

**Comment by maggiben** [comment]
sacamos el spinner y ocultamos el boton cuando el usuario se hace fan
