### ISSUE TITLE
Escudos de clubes cortados

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#369]
![captura de pantalla 2013-07-10 a la s 5 10 27 pm](https://f.cloud.github.com/assets/3672914/777606/dd780134-e99c-11e2-9df8-7745a32350aa.png)
![captura de pantalla 2013-07-10 a la s 5 10 31 pm](https://f.cloud.github.com/assets/3672914/777607/df9a69a2-e99c-11e2-865d-6cca853731f1.png)
![captura de pantalla 2013-07-10 a la s 5 10 40 pm](https://f.cloud.github.com/assets/3672914/777608/e5038554-e99c-11e2-85a0-7e4c8b843fd5.png)
![captura de pantalla 2013-07-10 a la s 5 10 50 pm](https://f.cloud.github.com/assets/3672914/777609/f1024dfe-e99c-11e2-937a-400b08478578.png)

**Comment by arraydude** [comment]
Problema de contenido

**Comment by lucasfc** [comment]
ok
