### ISSUE TITLE
Pulir Items de Muro 

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#37]
- Video
- Foto
- Album
- Post
- Compartido

Pulir estos elementos en el muro . mas alla de lo funcional.

**Comment by lucasfc** [comment]
Cuando hacemso esto @fansworld-claudio . q prioridad tiene_

**Comment by claudiorodriguez** [comment]
@lucasfc @arraydude Cuando terminemos con la home/canales y con Perfiles (home), nos abocamos a los detalles de perfiles, vídeos, etc, y entre eso el muro
