### ISSUE TITLE
Agregar boton de SER FAN.

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#372]
O en avatar o abajo de "cantidad de videos"
![captura de pantalla 2013-07-10 a la s 5 41 47 pm](https://f.cloud.github.com/assets/3672914/777800/d73ae534-e9a1-11e2-8769-9a93115e775b.png)

**Comment by arraydude** [comment]
![captura de pantalla 2013-07-11 a la s 2 38 22 pm](https://f.cloud.github.com/assets/631997/783449/d4049ef0-ea50-11e2-9942-6e19b77304c9.png)
