### ISSUE TITLE
Sugerencias en columna relacionados. 

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#379]
Habria que maquetar esto. No se si ya esta pero trae data de Invitar.

![captura de pantalla 2013-07-11 a la s 7 05 26 pm](https://f.cloud.github.com/assets/3672914/785184/12b56934-ea76-11e2-8c2e-e113925e6695.png)

**Comment by lucasfc** [comment]
@arraydude como ves esto? sabes si estaba maquetado?

**Comment by arraydude** [comment]
Que yo sepa no estaba maquetado @lucasfc
