### ISSUE TITLE
Fb connect -  No se muestra la imagen de FW cuando se quiere hacer FB connect.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#388]
Fb connect -  

No se muestra la imagen de FW cuando se quiere hacer FB connect.
![captura de pantalla 2013-07-12 a la s 12 21 17](https://f.cloud.github.com/assets/4354380/788951/0124866e-eb07-11e2-87e6-9fdfc8e92305.png)

**Comment by arraydude** [comment]
@vickychili necesitaria dos imagenes del logo de FW , una de 16x16 y otra de 75x75

**Comment by vickychili** [comment]
![app_fb75](https://f.cloud.github.com/assets/5075448/938734/6576c61e-0104-11e3-9214-c397a397e776.jpg)
![app_fb16](https://f.cloud.github.com/assets/5075448/938735/65778914-0104-11e3-8659-d6fb2f362865.jpg)
ahí te paso con el logo de fw con sm

**Comment by arraydude** [comment]
gracias @vickychili
