### ISSUE TITLE
Video - Despues de ver un video, el boton de invitar esta debajo de la flecha de scroll.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#391]
Video - 

Despues de ver un video, el boton de invitar esta debajo de la flecha de scroll.
![captura de pantalla 2013-07-12 a la s 13 46 15](https://f.cloud.github.com/assets/4354380/789544/4226605e-eb13-11e2-9826-8af542bfc8e5.png)

**Comment by arraydude** [comment]
@marucolona no lo puedo reproducir, en que resolución lo estas viendo ?

**Comment by marucolona** [comment]
@arraydude Ahora se ve bien, no esta pasando, cerralo nomas!
