### ISSUE TITLE
Home - No anda el boton de watch later en la home. 

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#394]
Home - 

No anda el boton de watch later en la home.  Al clickear no se agrega a la playlist.
![captura de pantalla 2013-07-12 a la s 14 07 14](https://f.cloud.github.com/assets/4354380/789682/d67a05ec-eb15-11e2-894d-c6c66bc386b1.png)

**Comment by maggiben** [comment]
@lucasfc y @arraydude estaría bueno cambiarle el color o algo despues de que se agrega a la lista, igual que en video detalle

**Comment by arraydude** [comment]
@maggiben totalmente, debiera ser ese el comportamiento, cualquier cosa agregale una class que yo despues le doy los estilos

**Comment by lucasfc** [comment]
@arraydude  paso el png de color ahora...

**Comment by lucasfc** [comment]
va .png...
![bt-watchlater-active](https://f.cloud.github.com/assets/3672914/799831/d7f64bc4-ed7c-11e2-8992-f679f6c6c59e.png)
