### ISSUE TITLE
Home - Comportamiento del boton de ser fan en perfiles.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#395]
Home - 

Cuando me aparecen los perfiles en la home, encuentro estos comportamientos:
1) Cuando clickeo en el +, no aparece ningún aviso de que hice fan
2) En muchos perfiles cuando clickeo en el + aparece un cartel diciendo que ya no soy fan de ese perfil.
3) En muchos casos después de que clickeo en el + aparece en boton de -, pero al clickear no pasa nada (y el boton tiene estado de clickeable)
4) En muchos casos el boton - aparece como grisado, sin posibilidad de clickear. 

![captura de pantalla 2013-07-12 a la s 14 45 56](https://f.cloud.github.com/assets/4354380/789944/c8f8067e-eb1c-11e2-901b-54384354f6ab.png)

**Comment by marucolona** [comment]
Si el usuario se hace fan de un usuario y refresca la pagina, el usuario le aparece nuevamente con el boton para agregar, pero al clickear no pasa nada. Y si entra a un perfil de un idolo y figura que es fan, al dejar de serlo, el botón sigue diciendo ya eres fan.

**Comment by maggiben** [comment]
El boton se esconde si ya se es fan, el boton de ser fan en la home del idolo lo chequeamos en un tk aparte
