### ISSUE TITLE
Perfiles - Area clickeable en fotos/videos/fans.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#396]
Perfiles -

Cuando voy a cualquier perfil, el area clickeable de  fotos/videos/fans al lado del splash es de la mitad del numero que aparezca para arriba

![captura de pantalla 2013-07-12 a la s 15 07 17](https://f.cloud.github.com/assets/4354380/790020/461a87ca-eb1e-11e2-9250-00d961d20b4b.png)

**Comment by anaibol** [comment]
Maru, fijate ahora que a mi me anda bien
