### ISSUE TITLE
Compartir - No puedo compartir contenido en FB o TW.

### ISSUE THREAD

**Issue by marucolona** [FansWorldTV/web#410]
Compartir - 

Cuando quiero compartir contenido en Facebook o Twitter, las pantallas se quedan en loading y en ningun momento se puede compartir la info. 

![captura de pantalla 2013-07-15 a la s 14 44 48](https://f.cloud.github.com/assets/4354380/799524/ae80f538-ed76-11e2-82b2-fd1616807b75.png)
![captura de pantalla 2013-07-15 a la s 14 44 31](https://f.cloud.github.com/assets/4354380/799525/b031e4b4-ed76-11e2-9e90-04f35c4312c6.png)

**Comment by anaibol** [comment]
maru, sabes que ahora estoy probando y ahora me esta andando compartir un video!
