### ISSUE TITLE
[ Backend ] searchHome tarda MUCHO

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#417]
El método searchHome de videoRepository esta tardando mas de la cuenta y hace que la espera para la carga de la home sea una tortura.

**Comment by juansanzone** [comment]
Tortura!

**Comment by juansanzone** [comment]
@arraydude , se testea en produccion con los datos reales directamente llamando al metodo, sin mas.. (logueado previamente) y responde bien. La carga es aceptable. No es problema del metodo aparentemente, el problema es que se llama a un mismo controller  (ajaxFilter) y se le pide, por un lado populares y por otro a los que sigues.. al mismo tiempo mediante ajax. y eso genera que deje de responder o se comporte inesperadamente. 

Testeamos llamada directa a follow aca: http://www2.fansworld.tv/home/list/follow

Fijate si el tiempo de respuesta te parece aceptable.

Una vez que implementamos que la home cargue todo por twig al momento de carga de la pagina y no por JS, deberiamos tener el problema solucionado. Te parece que dejemos en stanby este ticket hasta verificar eso? :)

**Comment by arraydude** [comment]
de acuerdo!

**Comment by juansanzone** [comment]
Lo cerramos, la home ya carga aceptablemente.
