### ISSUE TITLE
Mobile - API -  Comments Remove

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#418]
Falla remover para el mismo usuario que subio el video. Ej:

Req:
http://svn.dodici.com.ar/app.php/api_v1/comment/103/remove
user_id=2
user_token=d1b62047708d3a7b8ea35b9fd19f524a9c6412f1
api_timestamp=1374501657
api_key=abcdef
api_signature=dd860a006f2e11246598558dc708031463af1a2a

Resp:
 code: 403
 message: "User cannot delete comment"

**Comment by nicolasjafelle** [comment]
El usuario de pruebas por las dudas es "juan.perez" y password "test"

**Comment by claudiorodriguez** [comment]
@hernangonzalez O sea, cuando el usuario cuyas credenciales estamos utilizando es el author del vídeo, y el author del comment no es el mismo usuario, no se puede borrar. ¿Entendí bien? Si es así, es por diseño eso. El usuario tiene autoridad sobre los comments de su propio muro, no sobre los de los muros de sus vídeos. Si les parece que tendría que poder hacerlo, lo evaluamos. Por ahora cierro.

**Comment by hernangonzalez** [comment]
@fansworld-claudio Ok, si es como debe funcionar, no es bug. Lo levanté justamente porque me pareció natural que si yo fuera el autor del comentario, pudiese borrarlo. Evaluemos el cambio.

**Comment by hernangonzalez** [comment]
No está funcionado borrar un comentario del que es dueño en un video.

**Comment by claudiorodriguez** [comment]
fixed
