### ISSUE TITLE
Videos de Fansworld click logo

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#421]
Gloria consulta q cuando se hace click en el logo de FW deberia traer SOLO los video de FW. Yo no recuerdo haber hablado esto , pero no me sonaria raro.
NO se si estoy muy deacuerdo si van a compartir LAYOUT. No se, creo que es sumarle una dificultad mas. De ser asi no se si se entenderia la diferencia entre CANALES y esta PAGINA de canales de FW. medio raro no?

**Comment by claudiorodriguez** [comment]
@lucasfc  El logo de fansworld por una cuestión de estándar tendría que ir a la raíz del sitio, al /, al home por defecto al que se entra al ingresar a www.fansworld.tv sin nada más.

**Comment by lucasfc** [comment]
Sip. Y ahi se mostrarian lso videos de Fw con el mismo layout actual de canales no?

**Comment by claudiorodriguez** [comment]
@lucasfc En realidad creo que tenemos que discutir un poco más el tema de la home. Los usuarios buscaban la home en "mi perfil". Por ahora dejaría a la home "/" a la que lleva el logo, como el listado que tenemos actualmente. Una vez que tengamos la página de "mi perfil" hecha medio home, haría que sea la home "/" del usuario loggeado. No sé si me explico bien.

**Comment by lucasfc** [comment]
@fansworld-claudio  Incluir a JC ...

**Comment by claudiorodriguez** [comment]
@juank85 weigh in please
