### ISSUE TITLE
Consistencia SER FAN

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#425]
@fansworld-claudio @arraydude luego de test de usabilidad.
Hacerse fan: unificar criterios algunas veces aparece + otras ser fan.

El + NO dio resultado, hay lugares en donde no entraba el ser fan y recurrimos al +/
El test dio mal. El user debe leer la accion que se propone.
Como ven ete codigo cromatico (viene de mobile).
los escucho. 

Independeintemente de esto hay que patronizar los botones de SER FAN en MEDIDAS. adjunto imagen ilustrativa.

![ser-fan](https://f.cloud.github.com/assets/3672914/843989/357e2084-f3ca-11e2-9337-80f88c532889.jpg)
 Hacerse fan 

 Ser fan en algunos dice la palabra en otros tiene el +. El + no es claro/no se entiende. Al igual que pasas con compartir no hay criterios unificados y eso confunde.

También para algunos fue confuso por que los amigos son fans. Uno se hace fan de un perfil, idolo banda, etc.

**Comment by lucasfc** [comment]
@arraydude despues vemos el detalle de los BTs. Queiro verlo con Clau primero.

**Comment by claudiorodriguez** [comment]
@lucasfc el código de colores me parece bien, tengámoslo en cuenta para otras cosas en el sitio, si entendí bien verde es acción, celeste es informativo, gris es inhabilitado o pendiente (por ejemplo cuando listemos videos pendientes de proceso para el usuario, tendrán que ir con alguna clave gris)

**Comment by juank85** [comment]
Estamos proponiendo una iconografía que nos sirva de branding para ese call to action, y en un futuro cercano quedar solo con el icono, identico al caso facebook, el Like primero era ICONO + TEXTO... luego fue solo ICONO
