### ISSUE TITLE
Issues Registro

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#427]
1) Resolver temas de registracion:: no encuentran/ven "crear cuenta"; no ven el mensaje cuando la cuenta se ha creado y se les avisa que recibirán un mail para verificarla;  no entienden los beneficios de para que registrarse (en la parte de texto de explicar los beneficios apoyate/te puede ayudar Santi).

Registracion

Cuando no usaron facebook connect no encontraron con claridad el botón de "crear cuenta". En los casos que lograron crearla el mensaje que aparece en la pantalla de "recibirás un mail para confirmar cuenta" no se ve. Frustra también a los usuarios el no poder tener un acceso inmediato y tener que ir al mail para confirmar la cuenta y recién poder ingresar.
Tampoco existe claridad para que/cuales son los beneficios de registrarse.

**Comment by lucasfc** [comment]
Agrandar campos, ref> 
![captura de pantalla 2013-07-23 a la s 6 46 17 pm](https://f.cloud.github.com/assets/3672914/845157/6d727884-f3e1-11e2-9367-8f0053b05fe3.png)

**Comment by lucasfc** [comment]
![login](https://f.cloud.github.com/assets/3672914/873856/4e45dcfa-f880-11e2-85d4-da404f40114a.jpg)
![recuperar-contrasena-form](https://f.cloud.github.com/assets/3672914/873438/8f8b4ffa-f877-11e2-9034-c5e0e66cd33a.jpg)
![nueva-cuenta](https://f.cloud.github.com/assets/3672914/873437/8f8240ea-f877-11e2-8cc2-4bf2b833545c.jpg)
![login](https://f.cloud.github.com/assets/3672914/873439/8f8cb05c-f877-11e2-9c0c-07343466dbb3.jpg)
![recuperar-contrasena](https://f.cloud.github.com/assets/3672914/873440/8f87731c-f877-11e2-8437-3a29583f2c58.jpg)

**Comment by lucasfc** [comment]
@fansworld-claudio propuestas de registro. El modulo ese de 1234 deberia mejorarlo. Esas acciones son viejas.

**Comment by lucasfc** [comment]
![registros3](https://f.cloud.github.com/assets/3672914/880165/715f19ee-f935-11e2-8a1b-388170a0e7c3.jpg)

**Comment by claudiorodriguez** [comment]
@lucasfc 
- el revisa tu email está bien, no te parece que convendría agregarle un ícono grande de un sobre? Tipo 256x256, algo bien visible
- me gusta que los campos del registro estén en una sola columna
- el formulario con el fondo rojo me gusta pero tendríamos que mantener cierta coherencia - cuando se termina el registro, tendría que aparecer el "revisa tu mail" en ese mismo cuadrado, sino es confuso mandarlo a otro estilo de pantalla. las dos opciones me parecen bien igual. me parece más claro que lo que tenemos ahora

**Comment by lucasfc** [comment]
Perfect @fansworld-claudio , coincido con  todo..
