### ISSUE TITLE
Consistencia Compartir

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#431]
2) Compartir: hay que modificar el modal que no se entiende (botones como seleccionar en que red estoy compartiendo, campo para agregar gente yo personalmente lo quitaría porque no le vieron ningún valor agregado y solo confundía pero fijate vos como te parece mejor resolverlo. También había un tema de inconsistencia en cuanto a iconos etc de compartir en distintas partes del sitio.

Compartir

Varios trataron de compartir un link de video en su muro. No les resulto muy user friendly/claro el tener un campo para compartir con personas especificas. El modal compartir es muy confuso. El segundo espacio que ademas se autocompleta  no lo entendio nadie. Tampoco es claro como seleccionar donde (en que red) compartir.

**Comment by lucasfc** [comment]
Eliminaria estos
![captura de pantalla 2013-07-29 a la s 4 43 47 pm](https://f.cloud.github.com/assets/3672914/874240/881b41b6-f887-11e2-90e9-f8ae11e67f7d.png)

*\* y unificaria los pops en estos
![pop-compartir](https://f.cloud.github.com/assets/3672914/874245/90fae250-f887-11e2-8044-a9245e36de48.jpg)

a primera vista parece super minimo pero creo que el usuario no va a tenr q pensar demasiado, no tiene tantas opciones para customizar su "Compartida".

**Comment by claudiorodriguez** [comment]
@lucasfc sí, creo que es mucho más fácil de entender. Los logos de las redes sociales llevarían a los compartir externo. Contemplaría por ahí ponerle como label al botón "Compartir en FW" o algo así

**Comment by lucasfc** [comment]
![pop-compartir](https://f.cloud.github.com/assets/3672914/888100/2b5968ae-fa08-11e2-9afb-f22968ee9279.jpg)

**Comment by claudiorodriguez** [comment]
@lucasfc vamos para adelante con algo así

**Comment by lucasfc** [comment]
@juank85 esto es lo ultimo hecho. ,Despues de una cirugia mayor, propongo esto para el compartir.

**Comment by juank85** [comment]
Roger that
