### ISSUE TITLE
Mobile - API -  User thumb (default)

### ISSUE THREAD

**Issue by hernangonzalez** [FansWorldTV/web#432]
Los usuarios que aun no subieron una imagen por defecto comenzaron a enviar una de Fansworld. Para este caso, necesitamos que se mantenga el mecanismo de no enviar nada. Ej:

http://svn.dodici.com.ar/app_dev.php/api_v1/user/63

**Comment by claudiorodriguez** [comment]
@hernangonzalez antes habíamos hecho que tire siempre una imagen porque no se quería recibir un null. Explicame bien qué necesitarían que devuelva.

**Comment by hernangonzalez** [comment]
Ok, seguimos como está. Voy a pedir la calidad que necesito. Gracias.
