### ISSUE TITLE
Logo SM

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#436]
(actualización de logo con SM;

**Comment by vickychili** [comment]
![logofw](https://f.cloud.github.com/assets/5075448/863173/0bacc77e-f604-11e2-85c1-ded03300ba51.png)

**Comment by arraydude** [comment]
@vickychili @lucasfc No le falta el (SM) al logo que pusiste vicky ?

**Comment by lucasfc** [comment]
@vickychili si le falta.

**Comment by vickychili** [comment]
![logofw](https://f.cloud.github.com/assets/5075448/926190/cead0942-ff86-11e2-8d46-5d9e3a670894.png)
ahí va.. recién lo veo u.u

**Comment by arraydude** [comment]
@vickychili Sigue sin tener el SM

**Comment by lucasfc** [comment]
lo tiene pero muy chico. ahi te lo agradamos

**Comment by vickychili** [comment]
![logofw](https://f.cloud.github.com/assets/5075448/926257/49fc2460-ff88-11e2-9c88-c5c14094c074.png)
ahora si..se veia muy peque
