### ISSUE TITLE
Consistencia Ver despues / Gustar

### ISSUE THREAD

**Issue by lucasfc** [FansWorldTV/web#441]
ThumbUp y reloj
![compartir](https://f.cloud.github.com/assets/3672914/873598/550c9e02-f87b-11e2-9511-f28fc7471795.jpg)

**Comment by arraydude** [comment]
@lucasfc necesitaria los iconos de thumbsup y watchlater

**Comment by juank85** [comment]
Muchachos, vamos a revisar esta sugerencia con @lucasfc por lo que les pido una pequeña pausa en este issue.

**Comment by arraydude** [comment]
Perfecto!
