### ISSUE TITLE
[ Refactor ] [ Backend ] [ ThingsController ] serializeEvent 

### ISSUE THREAD

**Issue by arraydude** [FansWorldTV/web#457]
Es un método useless ?, o es indispensable para algo, se puede borrar?

serializeEvent() en ThingsController , line: 434

**Comment by anaibol** [comment]
@juansanzone

**Comment by juansanzone** [comment]
que narinas metidas @anaibol

**Comment by juansanzone** [comment]
Se puede borrar.
