### ISSUE TITLE
Serializer data del usuario logueado

### ISSUE THREAD

**Issue by maggiben** [FansWorldTV/web#458]
Nesecitamos crear una twig extension que serialise los datos del usuario para poder usarlo en aquellas funciones que requieran por ejemplo:
user_videos en UserController: (@Route("/u/{username}/videos", name="user_videos"))
De momento el metodo deberia devolver la ruta a los videos usuario actualmente logueado cuando el parametro username es null

**Comment by juansanzone** [comment]
Esta en proceso

**Comment by juansanzone** [comment]
Testeado, close
